// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!WQYQPOOOhQPO'#CdOOQO'#Ci'#CiOOQO'#Ce'#CeQYQPOOOOQO,59O,59OOyQPO,59OOOQO-E6c-E6cOOQO1G.j1G.j",
  stateData: "![~O[OSPOS~ORQOSQOTQOVPO~ORQOSQOTQOUTOVPO~ORQOSQOTQOUWOVPO~O",
  goto: "u^PPPPPPPP_ePPPoXQOPSUQSOQUPTVSUXROPSU",
  nodeNames: "⚠ LineComment Program Identifier String Boolean ) ( Application",
  maxTerm: 13,
  nodeProps: [
    ["openedBy", 6,"("],
    ["closedBy", 7,")"]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%V~R[XYwYZw]^wpqwrs!Yst#vxy$Uyz$Z!]!^$`!c!}$w#R#S$w#T#o$w~|S[~XYwYZw]^wpqw~!]VOr!Yrs!rs#O!Y#O#P!w#P;'S!Y;'S;=`#p<%lO!Y~!wOS~~!zRO;'S!Y;'S;=`#T;=`O!Y~#WWOr!Yrs!rs#O!Y#O#P!w#P;'S!Y;'S;=`#p;=`<%l!Y<%lO!Y~#sP;=`<%l!Y~#yQ#Y#Z$P#h#i$P~$UOT~~$ZOV~~$`OU~~$eSP~OY$`Z;'S$`;'S;=`$q<%lO$`~$tP;=`<%l$`~$|RR~!c!}$w#R#S$w#T#o$w",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
